import { PaymentStatusEnum } from '@lib/contracts/billing/enums/payment-status.enum';
import { ApiProperty } from '@nestjs/swagger';
import { IsEnum, IsNotEmpty, IsNumber, IsOptional, IsString, IsUUID } from 'class-validator';
import { TransactionTypeDto } from './transaction-type.dto';
import { InvoiceDto } from '../../invoice/dto/invoice.dto';
import { PaymentTypeDto } from '../../payment/dto/payment-type.dto';
import { PaymentChannelDto } from '../../payment/dto/payment-channel.dto';
import { PaymentProviderEnum } from '@lib/contracts/billing/enums/payment-provider.enum';

export class TransactionDto {
    @ApiProperty({description: 'Unique ID of the transaction (UUID generated by the system)',example: 'e2d4c7b2-51b2-4d6f-a3aa-0f7d728c6f22', })
    @IsUUID()
    @IsOptional()
    transaction_id: string;

    @ApiProperty({description: 'ID of the payment type used',example: '1',})
    @IsNotEmpty()
    payment_type_id: PaymentTypeDto;

    @ApiProperty({description: 'Channel for payment type', example: 'MTN Mobile Money'})
    @IsNotEmpty()
    payment_channel: PaymentChannelDto;

    @ApiProperty({description: 'Payment provider used for the transaction',enum: PaymentProviderEnum,example: PaymentProviderEnum.PAYSTACK,})
    @IsEnum(PaymentProviderEnum)
    provider: PaymentProviderEnum

    @ApiProperty({description: 'Date and time when the transaction occurred',example: '2025-05-02T15:45:00.000Z',})
    @IsNotEmpty()
    transaction_date: Date;

    @ApiProperty({description: 'Optional notes or details about the transaction',example: 'Payment made via Paystack using debit card',required: false,})
    @IsOptional()
    @IsString()
    transaction_details?: string;

    @ApiProperty({description: 'ID of the transaction type',example: '1',})
    @IsNotEmpty()
    transaction_type_id: TransactionTypeDto;

    @ApiProperty({description: 'Invoice ID this transaction is associated with',example: 'INV-20240501-007',})
    @IsString()
    @IsNotEmpty()
    invoice_number: InvoiceDto;

    @ApiProperty({description: 'Total transaction amount',example: 250.75,})
    @IsNumber()
    @IsNotEmpty()
    transaction_amount: number;

    @ApiProperty({description: 'Current payment status of the transaction',enum: PaymentStatusEnum,example: PaymentStatusEnum.Paid,})
    @IsEnum(PaymentStatusEnum)
    transaction_status: PaymentStatusEnum;

    @ApiProperty({description: 'Reference number from the payment provider (e.g., Paystack reference)',example: 'psk_ref_87hjsd8hjsa',})
    @IsString()
    @IsNotEmpty()
    reference_number: string;
}
